
services:
  postgres: 
    image: postgres:16-alpine
    container_name: wedding_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: kamal
      POSTGRES_PASSWORD: kamalov_wedding
      POSTGRES_DB: wedding_db
    ports:
      - "5434:5432"
    volumes:
      - wedding_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kamal -d wedding_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  wedding_db:
  